# Generated by Django 3.1.7 on 2022-01-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='refersh_token',
            new_name='refresh_token',
        ),
    ]
